In [1]:
import pandas as pd

In [3]:


# Using a different encoding based on the detection
df = pd.read_csv('Indian_startup_funding.csv', encoding='ISO-8859-1')

In [4]:
df

,S.No,Date dd/mm/yyyy,Startup Name,Industry Vertical,Sub Vertical,City Location,Investors Name,Investment Type,Amount in USD,Remarks
0,1,9/1/2020,BYJUS,E-Tech,E-learning,Bengaluru,"General Atlantic, Prosus, Peak XV, Sofina, Cha...",Private Equity Round,"40,00,00,000",NaN
1,2,13-01-2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"1,00,48,394",NaN
2,3,9/1/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"3,83,58,860",NaN
3,4,2/1/2020,wealthbucket,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,2/1/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29-01-2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29-01-2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30-01-2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30-01-2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31-01-2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [5]:
df.columns

Index(['S.No', 'Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical',
       'Sub Vertical', 'City  Location', 'Investors Name', 'Investment Type',
       'Amount in USD', 'Remarks'],
      dtype='object')

In [8]:
df = df.drop(columns=['S.No','Date dd/mm/yyyy','Startup Name','Remarks'])

In [10]:
df.to_csv('data.csv', index=False)